### ISSUE TITLE
Add support of creating objects in code blocks

### ISSUE THREAD

**Issue by jsking** [rlc2/pygame_maker#4]

**Comment by rlc2** [comment]
Added in commit aad03e60.
Find the action name in pygame_maker/actions/action.py inside an ACTION_DATA_YAML dict; the order and number of parameters following the action's name should be supplied as arguments to the function.
Therefore, to call `create_object_with_velocity()` from user code:
```
ACTION_DATA_YAML = """
...
    create_object_with_velocity:
      - object: common_object
      - position.x: common_position
      - position.y: common_position
      - speed: common_speed
      - direction:
            type: float
            default: 0.0
      - child_instance:
            type: bool
            default: False
      - relative: common_relative
...
"""
```
The above excerpt shows the arguments needed:
1. `object` is a string naming an object type
2. `position.x` is an integer X coordinate
3. `position.y` is an integer Y coordinate
4. `speed` is a decimal number for the object's movement speed
5. `direction` is a decimal number for the direction of motion in degrees
6. `child_instance` if true, means create the new object as a child of the current object
7. `relative` if true, means interpret position, speed, direction as relative to the current object
The "current object" refers to the object instance that executed the code block.
Remember that the language parser won't recognize bare function calls, so you need to use it in an assignment, E.G.:
```
ok = create_object_with_velocity('obj_UFO', 20+randint(screen_width-40), 0, 1.0, 180.0, false, false)
```
This should create an instance of `obj_UFO` at the top of the screen that moves downward at 1 pixel per frame.  The variable `ok` will equal 1 if the action was successfully called, 0 otherwise (these can also be compared with booleans true and false).
