### ISSUE TITLE
mouse_global_left events only fire if cursor is on object

### ISSUE THREAD

**Issue by jsking** [rlc2/pygame_maker#5]
```YAML
        mouse_global_left_pressed:
          - set_variable_value:
              variable: mouseDown
              value: 0
        mouse_global_left_released:
          - set_variable_value:
              variable: mouseDown
              value: -1
```
